In [2]:
# broadcasting with a scalar

import numpy as np

arr1 = np.array([1,2,3,4,5]);

result = arr1 + 10;

print(result);

# broadcasting with two arrays

arr2 = np.array([3,4,5,6,7]);

res = arr1 + arr2;

print(res);

# broadcasting a 2d array with 1d array

arr3 = np.array([[1,2,3],[4,5,6]]);

arr4 = np.array([3,4,5]);

result = arr3 + arr4;

print(result);

[11 12 13 14 15]
[ 4  6  8 10 12]
[[ 4  6  8]
 [ 7  9 11]]


In [6]:
# normalizing data using broadcasting
import numpy as np

data = np.array([[1,2,3],[4,5,6],[7,8,9]]);
print(data);

mean = data.mean(axis=0);
print(mean);
std = data.std(axis=0);
print(std);

normalized_data = (data-mean)/std;
print(normalized_data);


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]
[2.44948974 2.44948974 2.44948974]
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
