In [4]:
import numpy as np

arr = np.array([1,2,3],dtype=np.float32); # explicit type
print(arr.dtype);
print(arr);


# convert float to int

arr_int = arr.astype(np.int32);
print(arr_int);



float32
[1. 2. 3.]
[1 2 3]


In [14]:
# reshaping and flattening arrays

arr = np.array([[1,2,3],[4,5,6]]);
print(arr);
print(arr.shape);

reshaped = arr.reshape((1,6));
print(reshaped)
flattened = arr.flatten(); # convert 2d -> 1D

print(flattened);

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]


In [23]:
# indexing and slicing
arr = np.array([10,20,30,40]);
print(arr[0]);
print(arr[-1]);

# slicing

print(arr[1:4]);
print(arr[:]);
print(arr[:5]);
print(arr[::2]);
print(arr);

sliced = arr[1:4];
print(sliced);
sliced[0] = 99;
print(arr);

10
40
[20 30 40]
[10 20 30 40]
[10 20 30 40]
[10 30]
[10 20 30 40]
[20 30 40]
[10 99 30 40]
