In [5]:
import numpy as np

# selecting multiple at the same time

arr = np.array([1,2,3,4,5]);

idx = [0, 2, 4];

print(arr[idx]);



[1 3 5]


In [8]:
# filter data

arr = np.array([3,4,5]);

mask = arr > 3;
print(mask);
print(arr[mask]);


[False  True  True]
[4 5]


In [19]:
# practice
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]]);
print(arr.shape);
print(arr.dtype);
print(arr.ndim);
print(arr.size);

arr1 = np.array([1.1,2.2,3.3]);
print(arr1);
arr_int = arr1.astype(np.int32);
print(arr_int);

arr2 = np.array([1,2,3,4,5,6]);

idx = [1,3,5];
print(arr2[idx]);

mask = arr2 % 2 == 0;
print(mask);
print(arr2[mask]);

arr3 = np.array([1,2,3,4,5,6,7,8,9]);
reshaped = arr3.reshape((3,3));
print(reshaped);


arr4 = np.array(list(range(100)));
mask = arr4 > 50;
print(arr4[mask]);



(3, 3)
int64
2
9
[1.1 2.2 3.3]
[1 2 3]
[2 4 6]
[False  True False  True False  True]
[2 4 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
 99]
