In [5]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]]);

print(arr);

rowSum = np.sum(arr,axis=0);
print(rowSum);

colSum = np.sum(arr,axis=1);
print(colSum);

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [7]:
# indexing in multidimensional Arrays

import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]]);

print(arr[1,2]);

print(arr[0:2,1:3]);

6
[[2 3]
 [5 6]]
