In [9]:
# numpy vs python lists


# adding two lists in python
import numpy as np;
import time;
size = 100;
list1 = list(range(size));
list2 = list(range(size));

start = time.time();
result = [x + y for x , y in zip(list1,list2)];
end = time.time();
print(end-start);


# numpy array

arr1 = np.array(list1);
arr2 = np.array(list2);

start = time.time();
result = arr1 + arr2;
end = time.time();
print(end-start);




0.00028777122497558594
0.0004105567932128906


In [14]:
import numpy as np

# creating a 1D Numpy array

arr1 = np.array([1,2,3,4,5]);
print(arr1);

# creating a 2d Nump array

arr2 = np.array([[1,2,3],[4,5,6]]);

print(arr2);

# checking type and shape
print(type(arr1));
print(arr1.shape);
print(arr2.shape);

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(5,)
(2, 3)


In [17]:
# memory efficiency - numpy vs lists

import sys

list_data = list(range(1000));

numpy_data = np.array(list_data);


print(sys.getsizeof(list_data));
print(numpy_data.nbytes);





8056
8000


In [4]:
# vectorization no more loops
import numpy as np
my_list = [1,2,3,4,5];

list_squares = [x ** 2 for x in my_list];

arr = np.array(my_list);

numpy_squares = arr ** 2;

print(numpy_squares);
print(list_squares);
temp = list(range(10,101));
arr = np.array(temp);
print(arr);

[ 1  4  9 16 25]
[1, 4, 9, 16, 25]
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [6]:
# practice

import numpy as np
import time;

list1 = [1,2,3,4];
list2 = [3,4,5,6];
start = time.time(); 
res1 = [x * y for x,y in zip(list1,list2)];
end = time.time();
print(end-start);
print(res1);

arr1 = np.array(list1);
arr2 = np.array(list2);
start = time.time();
res2 = arr1 * arr2;
end = time.time();
print(res2);
print(end - start);



0.0003209114074707031
[3, 8, 15, 24]
[ 3  8 15 24]
0.0002455711364746094
